[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "swingmusic"
version = "2.0.2"
description = "Swing Music"
readme = "README.md"
requires-python = ">=3.11, <3.12"

dependencies = [
    "colorgram.py>=1.2.0",
    "Flask>=3.1.0",
    "Flask-Cors>=3.0.10",
    "flask-openapi3==3.0.2",
    "flask-compress>=1.13",
    "flask-jwt-extended>=4.6.0",
    "ffmpeg-python>=0.2.0",
    "locust>=2.20.1",
    "memory-profiler>=0.61.0",
    "pillow>=11.1.0",
    "psutil>=5.9.4",
    "pillow>=11.1.0",
    "pendulum>=3.0.0",
    "rapidfuzz==3.11.0",
    "requests>=2.27.1",
    "show-in-file-manager>=1.1.4",
    "setproctitle>=1.3.2",
    "schedule>=1.2.2",
    "sqlalchemy>=2.0.31",
    "sortedcontainers>=2.4.0",
    "tabulate>=0.9.0",
    "tqdm>=4.65.0",
    "tinytag>=2.0.0",
    "Unidecode>=1.3.6",
    "watchdog>=4.0.0",
    "xxhash>=3.4.1",
    "waitress>=3.0.2; sys_platform == 'win32'",
    "bjoern >=3.2.2; sys_platform != 'win32'"
]

[project.scripts]
swingmusic = "swingmusic.__main__:main"


[project.urls]
Homepage = "https://swingmx.com/"
Repository = "https://github.com/swingmx/swingmusic"
Documentation = "https://swingmx.com/guide/introduction.html"
Issues = "https://github.com/swingmx/swingmusic/issues"


[project.optional-dependencies]
dev = [
    "pyinstaller==6.12.0",
]
docs = [
    "sphinx",
    "furo",
    "sphinx_design",
    "myst_parser",
    "sphinx",
    "sphinx-autodoc2",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
swingmusic = ["src/swingmusic/client/*"]