[project]
name = "swing_music"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "pillow>=11.1.0",
    "Flask>=3.1.0",
    "Flask-Cors>=3.0.10",
    "requests>=2.27.1",
    "colorgram.py>=1.2.0",
    "tqdm>=4.65.0",
    "rapidfuzz>=2.13.7",
    "tinytag>=2.0.0",
    "Unidecode>=1.3.6",
    "psutil>=5.9.4",
    "show-in-file-manager>=1.1.4",
    "flask-compress>=1.13",
    "tabulate>=0.9.0",
    "setproctitle>=1.3.2",
    "locust>=2.20.1",
    "waitress>=2.1.2",
    "watchdog>=4.0.0",
    "pendulum>=3.0.0",
    "flask-jwt-extended>=4.6.0",
    "sqlalchemy>=2.0.31",
    "memory-profiler>=0.61.0",
    "sortedcontainers>=2.4.0",
    "xxhash>=3.4.1",
    "ffmpeg-python>=0.2.0",
    "schedule>=1.2.2",
    "flask-openapi3>=4.0.3",
    "pillow>=11.1.0",
    "gevent>=24.11.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.11.1",
]
