[tool.poetry]
name = "Swing music player"
version = "0.1.0"
description = ""
authors = ["geoffrey45 <geoffreymungai45@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
Flask = "^2.0.2"
Flask-Cors = "^3.0.10"
requests = "^2.27.1"
watchdog = "^3.0.0"
gunicorn = "^20.1.0"
Pillow = "^9.0.1"
"colorgram.py" = "^1.2.0"
tqdm = "^4.65.0"
rapidfuzz = "^2.13.7"
tinytag = "^1.8.1"
Unidecode = "^1.3.6"
psutil = "^5.9.4"
show-in-file-manager = "^1.1.4"
pendulum = "^2.1.2"
flask-compress = "^1.13"
tabulate = "^0.9.0"
setproctitle = "^1.3.2"
flask-restful = "^0.3.10"

[tool.poetry.dev-dependencies]
pylint = "^2.15.5"
pytest = "^7.1.3"
hypothesis = "^6.56.3"

[tool.poetry.dev-dependencies.black]
version = "^22.6.0"
allow-prereleases = true



[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[pytest]
console_output_style = "classic"
testpaths = "tests"
